apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxmox-exporter.fullname" . }}
  labels:
    {{- include "proxmox-exporter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "proxmox-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "proxmox-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "proxmox-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.config.port | default 8080 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
          env:
            - name: PROXMOX_EXPORTER_LOG_LEVEL
              value: '{{ .Values.config.log_level }}'
            - name: PROXMOX_EXPORTER_PROXMOX_API_INSECURE
              value: '{{ .Values.config.api_insecure }}'
            {{- if .Values.config.endpoints }}
            - name: PROXMOX_EXPORTER_PROXMOX_ENDPOINTS
              value: '{{ .Values.config.endpoints }}'
            {{- end }}
            {{- if .Values.config.token }}
            - name: PROXMOX_EXPORTER_PROXMOX_TOKEN
              value: '{{ .Values.config.token }}'
            {{- end }}
            {{- if .Values.config.tokenID }}
            - name: PROXMOX_EXPORTER_PROXMOX_TOKEN_ID
              value: '{{ .Values.config.tokenID }}'
            {{- end }}
            - name: PROXMOX_EXPORTER_SERVER_ADDR
              value: '{{ .Values.config.addr | default "0.0.0.0" }}'
            - name: PROXMOX_EXPORTER_SERVER_PORT
              value: '{{ .Values.config.port | default 8080 }}'
          {{- if and .Values.config.secretRef .Values.config.secretRef.name }}
          envFrom:
            - secretRef:
                {{- toYaml .Values.config.secretRef | nindent 16 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
