{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "proxmox-exporter.fullname" . }}
  labels:
    {{- include "proxmox-exporter.labels" . | nindent 4 }}
spec:
  groups:
    - name: ProxmoxNodes
      rules:
        - alert: ProxmoxNodeDown
          annotations:
            title: Proxmox node {{ $labels.node }} is down
          expr: |
            proxmox_node_up == 0
          for: 1m
          labels:
            severity: critical
        - alert: ProxmoxNodeTargetLost
          annotations:
            title: Proxmox node up metric absent for {{ $labels.node }}
            description: Something wrong with the exporter, the Proxmox API server(s) it is configured to make requests to, or the server the exporter is running on
          expr: |
            absent_over_time(proxmox_node_up[1h])
          for: 1m
          labels:
            severity: critical
        - alert: ProxmoxGuestDown
          annotations:
            title: Proxmox guest {{ $labels.name }} is down
            description: Guest {{ $labels.name }} of type {{ $labels.type }} on node {{ $labels.node }} is down
          expr: |
            proxmox_guest_up == 0
          for: 1m
          labels:
            severity: critical
        - alert: ProxmoxGuestTargetLost
          annotations:
            title: Proxmox guest up metric absent for {{ $labels.name }}
            description:  Guest {{ $labels.name }} of type {{ $labels.type }} on node {{ $labels.node }} may be down
          expr: |
            absent_over_time(proxmox_guest_up[1h])
          for: 1m
          labels:
            severity: critical
{{- end }}
