{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "proxmox-exporter.fullname" . }}
  labels:
    {{- include "proxmox-exporter.labels" . | nindent 4 }}
spec:
  groups:
    - name: ProxmoxNodes
      rules:
        {{- with .Values.prometheusRule.additionalRules }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.prometheusRule.enableBuiltinRules }}
        - alert: ProxmoxNodeDown
          annotations:
            summary: Proxmox node {{ printf "{{ $labels.node }}" }} is down
            description: Check the alerting Proxmox host
          expr: |
            proxmox_node_up == 0
          for: 1m
          labels:
            severity: critical
        - alert: ProxmoxNodeTargetLost
          annotations:
            summary: Proxmox node up metric absent for {{ printf "{{ $labels.node }}" }}
            description: Something wrong with the exporter, the Proxmox API server(s) it is configured to make requests to, or the server the exporter is running on
          expr: |
            absent_over_time(proxmox_node_up[1h])
          for: 1m
          labels:
            severity: critical

        - alert: ProxmoxGuestDown
          annotations:
            summary: Proxmox guest {{ printf "{{ $labels.name }}" }} is down
            description: Guest {{ printf "{{ $labels.name }}" }} of type {{ printf "{{ $labels.type }}" }} on node {{ printf "{{ $labels.node }}" }} is down
          expr: |
            proxmox_guest_up == 0
          for: 1m
          labels:
            severity: critical
        - alert: ProxmoxGuestTargetLost
          annotations:
            summary: Proxmox guest up metric absent for {{ printf "{{ $labels.name }}" }}
            description:  Guest {{ printf "{{ $labels.name }}" }} of type {{ printf "{{ $labels.type }}" }} on node {{ printf "{{ $labels.node }}" }} may be down
          expr: |
            absent_over_time(proxmox_guest_up[1h])
          for: 1m
          labels:
            severity: critical

        - alert: ProxmoxDiskUnhealthy
          annotations:
            summary: Proxmox disk {{ printf "{{ $labels.devpath }}" }} is unhealthy
            description: The disk {{ printf "{{ $labels.devpath }}" }} in node {{ printf "{{ $labels.node }}" }} is reporting unhealthy in SMART tests
          expr: |
            proxmox_node_disk_smart_status == 0
          for: 1m
          labels:
            severity: critical
        - alert: ProxmoxDiskTargetLost
          annotations:
            summary: Lost metrics for Proxmox disk {{ printf "{{ $labels.devpath }}" }}
            description:  The disk {{ printf "{{ $labels.devpath }}" }} in node {{ printf "{{ $labels.node }}" }} is not showing up in metrics from Proxmox anymore
          expr: |
            absent_over_time(proxmox_node_disk_smart_status[1h])
          for: 1m
          labels:
            severity: critical

        - alert: ProxmoxCertificateExpiring
          annotations:
            summary: Proxmox certificate on node {{ printf "{{ $labels.node }}" }} is expiring in a week
            description: The certificate with subject {{ printf "{{ $labels.subject }}" }} on that node is expiring in {{ printf "{{ $value }}" }} days
          expr: |
            proxmox_node_days_until_cert_expiration < 7
          for: 5m
          labels:
            severity: critical
        - alert: ProxmoxCertificateExpiringWarning
          annotations:
            summary: Proxmox certificate on node {{ printf "{{ $labels.node }}" }} is expiring soon
            description: The certificate with subject {{ printf "{{ $labels.subject }}" }} on that node is expiring in {{ printf "{{ $value }}" }} days
          expr: |
            proxmox_node_days_until_cert_expiration < 14
          for: 5m
          labels:
            severity: warning

        - alert: ProxmoxUnsharedStorageNearlyFull
          annotations:
            summary: Proxmox storage volume {{ printf "{{ $labels.node }}" }}/{{ printf "{{ $labels.storage }}" }} nearly full
            description: Volume of type {{ printf "{{ $labels.type }}" }} is {{ printf "{{ $value }}" }}% full
          expr: |
            100 * (sum by (storage,node) (proxmox_node_storage_used_bytes{shared="false"}) / sum by (storage,node) (proxmox_node_storage_total_bytes)) > 90
          for: 5m
          labels:
            severity: critical
        - alert: ProxmoxUnsharedStorageFilling
          annotations:
            summary: Proxmox storage volume {{ printf "{{ $labels.node }}" }}/{{ printf "{{ $labels.storage }}" }} nearly full
            description: Volume of type {{ printf "{{ $labels.type }}" }} is {{ printf "{{ $value }}" }}% full
          expr: |
            100 * (sum by (storage,node) (proxmox_node_storage_used_bytes{shared="false"}) / sum by (storage,node) (proxmox_node_storage_total_bytes)) > 80
          for: 5m
          labels:
            severity: warning

        - alert: ProxmoxSharedStorageNearlyFull
          annotations:
            summary: Proxmox shared storage volume {{ printf "{{ $labels.storage }}" }} nearly full
            description: Volume of type {{ printf "{{ $labels.type }}" }} is {{ printf "{{ $value }}" }}% full
          expr: |
            100 * (sum by (storage) (proxmox_node_storage_used_bytes{shared="true"}) / sum by (storage) (proxmox_node_storage_total_bytes)) > 90
          for: 5m
          labels:
            severity: critical
        - alert: ProxmoxSharedStorageFilling
          annotations:
            summary: Proxmox shared storage volume {{ printf "{{ $labels.storage }}" }} nearly full
            description: Volume of type {{ printf "{{ $labels.type }}" }} is {{ printf "{{ $value }}" }}% full
          expr: |
            100 * (sum by (storage) (proxmox_node_storage_used_bytes{shared="true"}) / sum by (storage) (proxmox_node_storage_total_bytes)) > 80
          for: 5m
          labels:
            severity: warning

        - alert: ProxmoxCPUAllocationHigh
          annotations:
            summary: Proxmox node {{ printf "{{ $labels.node }}" }} has {{ printf "{{ $value }}" }}% of its CPU allocated to guests
            description: It is recommended to keep more of your node's CPU unallocated for use by PVE and other server applications your Proxmox node runs
          expr: |
            100 * (proxmox_node_cpus_allocated / proxmox_node_cpus_total) > 90
          for: 5m
          labels:
            severity: critical
        - alert: ProxmoxMemoryAllocationHigh
          annotations:
            summary: Proxmox node {{ printf "{{ $labels.node }}" }} has {{ printf "{{ $value }}" }}% of its memory allocated to guests
            description: It is recommended to keep more of your node's memory unallocated for use by PVE and other server applications your Proxmox node runs
          expr: |
            100 * (proxmox_node_memory_allocated_bytes / proxmox_node_memory_total_bytes) > 90
          for: 5m
          labels:
            severity: critical
        {{- end }}
{{- end }}
