name: Test/Lint/Fmt/Vet
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1
    env:
      GOFLAGS: "-buildvcs=false"
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...

      - name: Vet
        run: go vet ./...

      - name: Mod download
        run: go mod download

      - name: Mod verify
        run: go mod verify

      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck -test ./...

      - name: Run errcheck
        run: |
          go install github.com/kisielk/errcheck@latest
          errcheck ./...

      - name: Run staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...

      - name: Run golint
        run: |
          go install golang.org/x/lint/golint
          golint -set_exit_status ./...
