name: Test/Lint/Fmt/Vet
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1
    env:
      GOFLAGS: "-buildvcs=false"
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...

      - name: Go Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Go Vet
        run: go vet ./...

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Go Mod Verify
        run: go mod verify

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck -test ./...

      - name: Install errcheck
        run: go install github.com/kisielk/errcheck@latest

      - name: Run errcheck
        run: errcheck ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golint
        run: go install go get -u golang.org/x/lint/golint

      - name: Run golint
        run: golint -set_exit_status ./...
